name: 'Generate Release Semantic'
description: 'This action calculates changes in releases using the conventional commits pattern as a base and sums it up with the last released tag, if no tag was released, the action uses the calculation of the current release as the new release.'
inputs:
  github-token:
    description: 'Personal access token to access the GitHub API'
    required: true
  
outputs:
  success:
    description: 'message success'
runs:
  using: 'node12'
  main: 'dist/index.js'